### ISSUE TITLE
Feature: User can search locations in the US

### ISSUE THREAD

**Issue by sanfordhuynh** [sanfordhuynh/Fetch-project#1]
## ⚙️ Feature

User can search locations

## 📐 Functionality

Create a search bar function that allows users to search different attractions, hotels, restaurants, etc...

## 🖼️ Wireframes

![Excursion](https://github.com/sanfordhuynh/Fetch-project/assets/16739580/998ffd30-3ec2-41ca-b437-28b160484b0f)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML/CSS Skeleton for the homepage
- [x] Add placement holders all the different navigation links 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Create a Fetch function for retrieving the Location data and description
- [x] Render the location data and display the information
- [x] Create another page by using dom elements to show the queried result of search using TripAdvisor API
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
