### ISSUE TITLE
Users can view multiple images of the search query

### ISSUE THREAD

**Issue by sanfordhuynh** [sanfordhuynh/Fetch-project#2]
## ⚙️ Feature

Users can view multiple images 

## 📐 Functionality

Create an image gallery pulled from the Tripadvisor API 

## 🖼️ Wireframes

![Excursion2](https://github.com/sanfordhuynh/Fetch-project/assets/16739580/e28ccb8b-be51-4be6-aac0-ef5703dd2a89)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Create arrow to go through picture gallery
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
