### ISSUE TITLE
Users can select reviews to view

### ISSUE THREAD

**Issue by sanfordhuynh** [sanfordhuynh/Fetch-project#3]
## ⚙️ Feature

Users can select reviews to view

## 📐 Functionality

Users can select reviews to view of the hotel, attraction, or restaurant

## 🖼️ Wireframes

![review](https://github.com/sanfordhuynh/Fetch-project/assets/16739580/06711cbc-7590-4986-b4c8-8087fcce1f29)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Use the emojicon to create the circles for review
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
