### ISSUE TITLE
User can read description of the search query

### ISSUE THREAD

**Issue by sanfordhuynh** [sanfordhuynh/Fetch-project#5]
## ⚙️ Feature

User can read description of the search query

## 📐 Functionality

User can read description of the search query so they have more information about the place.

## 🖼️ Wireframes

![review](https://github.com/sanfordhuynh/Fetch-project/assets/16739580/1b1d5091-685c-4b9d-b93d-4f096540762e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the function to fetch API from TripAdvisor to display the description of the search query
- [x] Create function to render the data of the location
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
